version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    user: root
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/node/app