name: docker-run

on: push

jobs:
  build:
    name: docker-run
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Build the docker
        run: |
          docker-compose run -rm app npm install
      - name: Run jest
        run: docker-compose run -rm app npm install @typescript-eslint/eslint-plugin@latest --save-dev
        run: docker-compose run --rm app npx eslint --fix ./src