name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      app:
        image: node:18
        user: root
        working_dir: /home/node/app
        ports:
          - 3000
        options: --name app --init --entrypoint npm

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and start container
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Install dependencies
        run: docker-compose run --rm app npm ci

      - name: Lint
        run: docker-compose run --rm app npm run lint